import { TopicData } from './types';

export const WORDS_PER_DAY = 20;
export const THINKING_TIME = 10;

export const TOPICS_RAW_DATA: TopicData = {
    "Environment": [
      { id: 1, term: "adjust", type: "v", definition: "điều chỉnh" },
      { id: 2, term: "modify", type: "v", definition: "sửa đổi" },
      { id: 3, term: "adopt", type: "v", definition: "nhận nuôi; áp dụng" },
      { id: 4, term: "awareness", type: "n", definition: "nhận thức" },
      { id: 5, term: "struggle", type: "n/v", definition: "sự đấu tranh, vật lộn" },
      { id: 6, term: "conflict", type: "n", definition: "mâu thuẫn, xung đột" },
      { id: 7, term: "contaminated", type: "adj", definition: "bị ô nhiễm" },
      { id: 8, term: "unequal", type: "adj", definition: "không bình đẳng" },
      { id: 9, term: "flight", type: "n", definition: "chuyến bay" },
      { id: 10, term: "footprint", type: "n", definition: "dấu chân" },
      { id: 11, term: "sustainable", type: "adj", definition: "bền vững" },
      { id: 12, term: "precise", type: "adj", definition: "chính xác" },
      { id: 13, term: "application", type: "n", definition: "ứng dụng" },
      { id: 14, term: "engine", type: "n", definition: "động cơ" },
      { id: 15, term: "appliance", type: "n", definition: "thiết bị" },
      { id: 16, term: "weapon", type: "n", definition: "vũ khí" },
      { id: 17, term: "renewable", type: "adj", definition: "có thể tái tạo" },
      { id: 18, term: "harmful", type: "adj", definition: "có hại" },
      { id: 19, term: "conscious", type: "adj", definition: "có ý thức" },
      { id: 20, term: "beneficial", type: "adj", definition: "có lợi" },
      { id: 21, term: "litter", type: "n", definition: "rác" },
      { id: 22, term: "demand", type: "n", definition: "nhu cầu" },
      { id: 23, term: "organic", type: "adj", definition: "hữu cơ" },
      { id: 24, term: "efficient", type: "adj", definition: "hiệu quả" },
      { id: 25, term: "plastic", type: "adj", definition: "làm bằng nhựa" },
      { id: 26, term: "exhibition", type: "n", definition: "triển lãm" },
      { id: 27, term: "facility", type: "n", definition: "cơ sở" },
      { id: 28, term: "refillable", type: "adj", definition: "có thể nạp đầy lại" },
      { id: 29, term: "bottle", type: "n", definition: "chai" },
      { id: 30, term: "divert", type: "v", definition: "làm chuyển hướng, phân luồng" },
      { id: 31, term: "distract", type: "v", definition: "làm xao lãng" },
      { id: 32, term: "alter", type: "v", definition: "thay đổi" },
      { id: 33, term: "alternative", type: "n", definition: "sự thay thế" },
      { id: 34, term: "requirement", type: "n", definition: "yêu cầu" },
      { id: 35, term: "movement", type: "n", definition: "phong trào, sự di chuyển" },
      { id: 36, term: "mission", type: "n", definition: "nhiệm vụ" },
      { id: 37, term: "combat", type: "v", definition: "chiến đấu, chống lại" },
      { id: 38, term: "spill", type: "n", definition: "sự tràn" },
      { id: 39, term: "creature", type: "n", definition: "sinh vật" },
      { id: 40, term: "magnitude", type: "n", definition: "độ lớn" },
      { id: 41, term: "theme", type: "n", definition: "chủ đề" },
      { id: 42, term: "plentiful", type: "adj", definition: "dồi dào" },
      { id: 43, term: "realistic", type: "adj", definition: "thực tế" },
      { id: 44, term: "private", type: "adj", definition: "riêng tư" },
      { id: 45, term: "devastating", type: "adj", definition: "có tính tàn phá" },
      { id: 46, term: "emission", type: "n", definition: "sự thải, khí thải" },
      { id: 47, term: "trend", type: "n", definition: "xu hướng" },
      { id: 48, term: "origin", type: "n", definition: "nguồn gốc" },
      { id: 49, term: "sewage", type: "n", definition: "nước thải" },
      { id: 50, term: "release", type: "v", definition: "thải ra, thả ra" },
      { id: 51, term: "landfill", type: "n", definition: "bãi chôn lấp" },
      { id: 52, term: "compost", type: "n", definition: "phân trộn" },
      { id: 53, term: "livestock", type: "n", definition: "gia súc" },
      { id: 54, term: "significant", type: "adj", definition: "đáng kể" },
      { id: 55, term: "controversy", type: "n", definition: "tranh cãi" },
      { id: 56, term: "obvious", type: "adj", definition: "rõ ràng" },
      { id: 57, term: "marine", type: "adj", definition: "thuộc biển" },
      { id: 58, term: "convey", type: "v", definition: "truyền tải" },
      { id: 59, term: "distribute", type: "v", definition: "phân phối" },
      { id: 60, term: "ecological", type: "adj", definition: "thuộc sinh thái" },
      { id: 61, term: "disrupt", type: "v", definition: "làm gián đoạn" },
      { id: 62, term: "frequent", type: "adj", definition: "thường xuyên" },
      { id: 63, term: "severe", type: "adj", definition: "nghiêm trọng" },
      { id: 64, term: "possibility", type: "n", definition: "khả năng" },
      { id: 65, term: "overuse", type: "n", definition: "việc sử dụng quá mức" },
      { id: 66, term: "organism", type: "n", definition: "sinh vật" },
      { id: 67, term: "quantity", type: "n", definition: "số lượng" },
      { id: 68, term: "chain", type: "n", definition: "chuỗi" },
      { id: 69, term: "biodiversity", type: "n", definition: "đa dạng sinh học" },
      { id: 70, term: "strategy", type: "n", definition: "chiến lược" },
      { id: 71, term: "potential", type: "adj", definition: "tiềm năng" },
      { id: 72, term: "impossible", type: "adj", definition: "bất khả thi" },
      { id: 73, term: "native", type: "adj", definition: "bản địa" },
      { id: 74, term: "tropical", type: "adj", definition: "thuộc nhiệt đới" },
      { id: 75, term: "endangered", type: "adj", definition: "nguy cấp" },
      { id: 76, term: "single-use", type: "adj", definition: "sử dụng một lần" },
      { id: 77, term: "extinct", type: "adj", definition: "tuyệt chủng" },
      { id: 78, term: "habitat", type: "n", definition: "môi trường sống" },
      { id: 79, term: "custom", type: "n", definition: "phong tục" },
      { id: 80, term: "preserve", type: "n/v", definition: "khu bảo tồn/bảo tồn" },
      { id: 81, term: "rapid", type: "adj", definition: "nhanh chóng" },
      { id: 82, term: "illegal", type: "adj", definition: "bất hợp pháp" },
      { id: 83, term: "threatened", type: "adj", definition: "bị đe dọa" },
      { id: 84, term: "biological", type: "adj", definition: "về mặt sinh học" },
      { id: 85, term: "widespread", type: "adj", definition: "trên diện rộng" },
      { id: 86, term: "deforestation", type: "n", definition: "nạn phá rừng" },
      { id: 87, term: "conservation", type: "n", definition: "sự bảo tồn" },
      { id: 88, term: "erosion", type: "n", definition: "sự xói mòn" },
      { id: 89, term: "supervise", type: "v", definition: "giám sát" },
      { id: 90, term: "poach", type: "v", definition: "săn bắt trộm" },
      { id: 91, term: "tusk", type: "n", definition: "ngà" },
      { id: 92, term: "rescue", type: "v", definition: "giải cứu" },
      { id: 93, term: "hunt", type: "v", definition: "săn" },
      { id: 94, term: "temporary", type: "adj", definition: "tạm thời" },
      { id: 95, term: "complex", type: "adj", definition: "phức tạp" },
      { id: 96, term: "train", type: "v", definition: "huấn luyện" },
      { id: 97, term: "emit", type: "v", definition: "phát ra" },
      { id: 98, term: "gibbon", type: "n", definition: "vượn" },
      { id: 99, term: "examine", type: "v", definition: "kiểm tra" },
      { id: 100, term: "express", type: "v", definition: "bày tỏ" },
      { id: 101, term: "monitor", type: "v", definition: "giám sát" },
      { id: 102, term: "recycle", type: "v", definition: "tái chế" },
      { id: 103, term: "reuse", type: "v", definition: "tái sử dụng" },
      { id: 104, term: "classify", type: "v", definition: "phân loại" },
      { id: 105, term: "critically", type: "adv", definition: "nghiêm trọng" },
      { id: 106, term: "survive", type: "v", definition: "sống sót" },
      { id: 107, term: "balance", type: "v", definition: "cân bằng" },
      { id: 108, term: "generate", type: "v", definition: "tạo ra" },
      { id: 109, term: "reintroduce", type: "v", definition: "đưa trở lại" },
      { id: 110, term: "recognise", type: "v", definition: "nhận ra" },
      { id: 111, term: "wildlife", type: "n", definition: "động vật hoang dã" },
      { id: 112, term: "enact", type: "v", definition: "ban hành" },
      { id: 113, term: "ecosystem", type: "n", definition: "hệ sinh thái" },
      { id: 114, term: "affordable", type: "adj", definition: "giá cả phải chăng" },
      { id: 115, term: "enthusiastic", type: "adj", definition: "nhiệt tình" },
      { id: 116, term: "fragile", type: "adj", definition: "mong manh" },
      { id: 117, term: "measure", type: "n", definition: "biện pháp" },
      { id: 118, term: "confine", type: "v", definition: "giam cầm" },
      { id: 119, term: "diverse", type: "adj", definition: "đa dạng" },
      { id: 120, term: "urgent", type: "adj", definition: "khẩn cấp" },
      { id: 121, term: "captivity", type: "n", definition: "sự giam cầm" },
      { id: 122, term: "immediate", type: "adj", definition: "ngay lập tức" },
      { id: 123, term: "undertake", type: "v", definition: "thực hiện" },
      { id: 124, term: "renew", type: "v", definition: "gia hạn" },
      { id: 125, term: "obey", type: "v", definition: "tuân thủ" },
      { id: 126, term: "restore", type: "v", definition: "khôi phục" },
      { id: 127, term: "coral reef", type: "np", definition: "rạn san hô" },
      { id: 128, term: "debris", type: "n", definition: "mảnh vụn" },
      { id: 129, term: "nursery", type: "n", definition: "vườn ươm" },
      { id: 130, term: "enhance", type: "v", definition: "tăng cường" },
      { id: 131, term: "profit", type: "n", definition: "lợi nhuận" },
      { id: 132, term: "strain", type: "n", definition: "áp lực" },
      { id: 133, term: "considerable", type: "adj", definition: "đáng kể" },
      { id: 134, term: "vulnerable", type: "adj", definition: "dễ bị tổn thương" },
      { id: 135, term: "clearance", type: "n", definition: "sự chặt phá" },
      { id: 136, term: "breed", type: "v", definition: "phối giống" },
      { id: 137, term: "degrade", type: "v", definition: "làm suy thoái" },
      { id: 138, term: "punishment", type: "n", definition: "hình phạt" },
      { id: 139, term: "alarming", type: "adj", definition: "đáng báo động" },
      { id: 140, term: "environmental", type: "adj", definition: "thuộc môi trường" },
      { id: 141, term: "activist", type: "n", definition: "nhà hoạt động" },
      { id: 142, term: "urge", type: "v", definition: "thúc giục, kêu gọi" },
      { id: 143, term: "boycott", type: "v", definition: "tẩy chay" },
      { id: 144, term: "protest", type: "v", definition: "biểu tình" },
      { id: 145, term: "significantly", type: "adv", definition: "đáng kể" },
      { id: 146, term: "electricity", type: "n", definition: "điện" },
      { id: 147, term: "greenhouse", type: "n", definition: "nhà kính" },
      { id: 148, term: "campaign", type: "n", definition: "chiến dịch" },
      { id: 149, term: "incentive", type: "n", definition: "sự khuyến khích, ưu đãi" }
    ],
    "Cultures": [
      { id: 1, term: "diversity", type: "n", definition: "sự đa dạng" },
      { id: 2, term: "immigrant", type: "n", definition: "người nhập cư" },
      { id: 3, term: "maintain", type: "v", definition: "duy trì" },
      { id: 4, term: "congestion", type: "n", definition: "sự tắc nghẽn" },
      { id: 5, term: "identity", type: "n", definition: "bản sắc" },
      { id: 6, term: "ancient", type: "adj", definition: "cổ xưa, lâu đời" },
      { id: 7, term: "origin", type: "n", definition: "nguồn gốc" },
      { id: 8, term: "custom", type: "n", definition: "phong tục" },
      { id: 9, term: "trace", type: "v", definition: "lần theo dấu vết" },
      { id: 10, term: "trend", type: "n", definition: "xu hướng" },
      { id: 11, term: "spicy", type: "adj", definition: "cay" },
      { id: 12, term: "savoury/savory", type: "adj", definition: "có vị thơm ngon đậm đà" },
      { id: 13, term: "cookery", type: "n", definition: "cách nấu ăn" },
      { id: 14, term: "cuisine", type: "n", definition: "ẩm thực" },
      { id: 15, term: "culture shock", type: "n", definition: "sốc văn hoá" },
      { id: 16, term: "occasion", type: "n", definition: "dịp" },
      { id: 17, term: "connected", type: "adj", definition: "kết nối" },
      { id: 18, term: "speciality/specialty", type: "n", definition: "đặc sản" },
      { id: 19, term: "globalisation/globalization", type: "n", definition: "toàn cầu hoá" },
      { id: 20, term: "highlight", type: "n", definition: "điểm nhấn" },
      { id: 21, term: "blend", type: "v", definition: "pha trộn, kết hợp" },
      { id: 22, term: "contemporary", type: "adj", definition: "đương thời" },
      { id: 23, term: "richness", type: "n", definition: "sự giàu có, sự phong phú" },
      { id: 24, term: "reflect", type: "v", definition: "phản ánh" },
      { id: 25, term: "barrier", type: "n", definition: "rào cản" },
      { id: 26, term: "rude", type: "adj", definition: "thô lỗ" },
      { id: 27, term: "insulting", type: "adj", definition: "xúc phạm" },
      { id: 28, term: "fusion", type: "n", definition: "sự pha trộn" },
      { id: 29, term: "comply", type: "v", definition: "tuân thủ" },
      { id: 30, term: "abide", type: "v", definition: "tuân theo" },
      { id: 31, term: "adhere", type: "v", definition: "tuân thủ, gắn bó" },
      { id: 32, term: "costume", type: "n", definition: "trang phục" },
      { id: 33, term: "inappropriately", type: "adv", definition: "không phù hợp" },
      { id: 34, term: "manners", type: "n", definition: "cách cư xử" },
      { id: 35, term: "taboo", type: "adj", definition: "điều cấm kỵ" },
      { id: 36, term: "punctuality", type: "n", definition: "sự đúng giờ" },
      { id: 37, term: "ceremony", type: "n", definition: "nghi lễ" },
      { id: 38, term: "ritual", type: "n", definition: "nghi lễ" },
      { id: 39, term: "feast", type: "n", definition: "tiệc lớn" },
      { id: 40, term: "norm", type: "n", definition: "quy tắc, chuẩn mực" },
      { id: 41, term: "prosperity", type: "n", definition: "sự thịnh vượng" },
      { id: 42, term: "gratitude", type: "n", definition: "lòng biết ơn" },
      { id: 43, term: "longevity", type: "n", definition: "sống thọ" },
      { id: 44, term: "honoured/honored", type: "adj", definition: "đáng kính" },
      { id: 45, term: "vibrant", type: "adj", definition: "sôi động" },
      { id: 46, term: "ancestor", type: "n", definition: "tổ tiên" }
    ],
    "Being Independent": [
      { id: 1, term: "independent", type: "adj", definition: "tự lập" },
      { id: 2, term: "effective", type: "adj", definition: "hiệu quả" },
      { id: 3, term: "include", type: "v", definition: "bao gồm" },
      { id: 4, term: "respect", type: "v", definition: "tôn trọng" },
      { id: 5, term: "manage", type: "v", definition: "quản lý" },
      { id: 6, term: "appreciate", type: "v", definition: "đánh giá cao" },
      { id: 7, term: "conflict", type: "n", definition: "mâu thuẫn" },
      { id: 8, term: "argument", type: "n", definition: "cuộc tranh luận" },
      { id: 9, term: "privacy", type: "n", definition: "sự riêng tư" },
      { id: 10, term: "occasionally", type: "adv", definition: "thỉnh thoảng" },
      { id: 11, term: "seek", type: "v", definition: "tìm kiếm" },
      { id: 12, term: "self-motivated", type: "adj", definition: "tự thúc đẩy" },
      { id: 13, term: "strict", type: "adj", definition: "nghiêm khắc" },
      { id: 14, term: "selfish", type: "adj", definition: "ích kỷ" },
      { id: 15, term: "control", type: "v", definition: "kiểm soát" },
      { id: 16, term: "essential", type: "adj", definition: "cần thiết" },
      { id: 17, term: "academic", type: "adj", definition: "học thuật" },
      { id: 18, term: "achieve", type: "v", definition: "đạt được" },
      { id: 19, term: "self-control", type: "n", definition: "tự kiểm soát" },
      { id: 20, term: "self-study", type: "n", definition: "tự học" },
      { id: 21, term: "self-defence", type: "n", definition: "tự vệ" },
      { id: 22, term: "self-service", type: "n", definition: "tự phục vụ" },
      { id: 23, term: "extracurricular", type: "adj", definition: "ngoại khóa" },
      { id: 24, term: "valuable", type: "adj", definition: "có giá trị" },
      { id: 25, term: "handle", type: "v", definition: "xử lý" },
      { id: 26, term: "challenge", type: "n", definition: "thử thách" },
      { id: 27, term: "life skill", type: "n", definition: "kỹ năng sống" },
      { id: 28, term: "viewpoint", type: "n", definition: "quan điểm" },
      { id: 29, term: "requirement", type: "n", definition: "yêu cầu" },
      { id: 30, term: "to-do list", type: "n", definition: "danh sách việc cần làm" },
      { id: 31, term: "career", type: "n", definition: "sự nghiệp" },
      { id: 32, term: "duty", type: "n", definition: "nhiệm vụ" },
      { id: 33, term: "habit", type: "n", definition: "thói quen" },
      { id: 34, term: "significant", type: "adj", definition: "quan trọng" },
      { id: 35, term: "time management", type: "n", definition: "quản lý thời gian" },
      { id: 36, term: "contribute", type: "v", definition: "đóng góp" },
      { id: 37, term: "budget", type: "v", definition: "lập ngân sách" },
      { id: 38, term: "focus", type: "v", definition: "tập trung" },
      { id: 39, term: "productively", type: "adv", definition: "hiệu quả" },
      { id: 40, term: "freshmen", type: "n", definition: "sinh viên năm nhất" },
      { id: 41, term: "diagnose", type: "v", definition: "chẩn đoán" },
      { id: 42, term: "struggle", type: "v", definition: "vật lộn" },
      { id: 43, term: "examine", type: "v", definition: "kiểm tra" },
      { id: 44, term: "assignment", type: "n", definition: "bài tập" },
      { id: 45, term: "deadline", type: "n", definition: "hạn chót" },
      { id: 46, term: "pleasant", type: "adj", definition: "dễ chịu" },
      { id: 47, term: "equal", type: "adj", definition: "bình đẳng" },
      { id: 48, term: "dependable", type: "adj", definition: "đáng tin cậy" },
      { id: 49, term: "affordable", type: "adj", definition: "giá cả phải chăng" },
      { id: 50, term: "hesitant", type: "adj", definition: "do dự" },
      { id: 51, term: "satisfactory", type: "adj", definition: "thoả đáng" },
      { id: 52, term: "summer break", type: "n", definition: "kỳ nghỉ hè" },
      { id: 53, term: "hands-on", type: "adj", definition: "thực tiễn, thực hành" },
      { id: 54, term: "behave", type: "v", definition: "cư xử" },
      { id: 55, term: "skip", type: "v", definition: "bỏ qua" },
      { id: 56, term: "gain", type: "v", definition: "đạt được" },
      { id: 57, term: "adjust", type: "v", definition: "điều chỉnh" },
      { id: 58, term: "consumption", type: "n", definition: "sự tiêu thụ" },
      { id: 59, term: "recipe", type: "n", definition: "công thức" },
      { id: 60, term: "feature", type: "n", definition: "đặc điểm" },
      { id: 61, term: "determined", type: "adj", definition: "quyết tâm" },
      { id: 62, term: "responsibility", type: "n", definition: "trách nhiệm" },
      { id: 63, term: "washing-up", type: "n", definition: "rửa bát đĩa" },
      { id: 64, term: "schedule", type: "n", definition: "lịch trình" },
      { id: 65, term: "purpose", type: "n", definition: "mục đích" },
      { id: 66, term: "disease", type: "n", definition: "bệnh" },
      { id: 67, term: "assistance", type: "n", definition: "trợ giúp" },
      { id: 68, term: "promote", type: "v", definition: "thúc đẩy" },
      { id: 69, term: "self-reliant", type: "adj", definition: "tự lập" },
      { id: 70, term: "dominant", type: "adj", definition: "chi phối, nổi bật nhất" },
      { id: 71, term: "decisive", type: "adj", definition: "quyết đoán, dứt khoát" },
      { id: 72, term: "satisfied", type: "adj", definition: "hài lòng" },
      { id: 73, term: "irresponsible", type: "adj", definition: "vô trách nhiệm" },
      { id: 74, term: "treat", type: "v", definition: "đối xử" },
      { id: 75, term: "motivate", type: "v", definition: "thúc đẩy" },
      { id: 76, term: "assign", type: "v", definition: "giao nhiệm vụ" },
      { id: 77, term: "routine", type: "n", definition: "thói quen hàng ngày" },
      { id: 78, term: "beneficial", type: "adj", definition: "có lợi" },
      { id: 79, term: "recovery", type: "n", definition: "phục hồi" },
      { id: 80, term: "progress", type: "n", definition: "tiến triển, tiến bộ" },
      { id: 81, term: "realistic", type: "adj", definition: "thực tế" },
      { id: 82, term: "specific", type: "adj", definition: "cụ thể" },
      { id: 83, term: "sensitive", type: "adj", definition: "nhạy cảm" },
      { id: 84, term: "voluntary", type: "adj", definition: "tình nguyện, tự nguyện" },
      { id: 85, term: "vulnerable", type: "adj", definition: "dễ bị tổn thương" },
      { id: 86, term: "generous", type: "adj", definition: "hào phóng" },
      { id: 87, term: "well-informed", type: "adj", definition: "hiểu biết rõ" },
      { id: 88, term: "enthusiastic", type: "adj", definition: "nhiệt tình" },
      { id: 89, term: "self-esteem", type: "n", definition: "lòng tự trọng" },
      { id: 90, term: "pressure", type: "n", definition: "áp lực" },
      { id: 91, term: "concentration", type: "n", definition: "sự tập trung" },
      { id: 92, term: "prioritise/prioritize", type: "v", definition: "ưu tiên" },
      { id: 93, term: "optimal", type: "adj", definition: "tối ưu" },
      { id: 94, term: "assess", type: "v", definition: "đánh giá" },
      { id: 95, term: "nominate", type: "v", definition: "đề cử" },
      { id: 96, term: "propose", type: "v", definition: "đề xuất" },
      { id: 97, term: "impact", type: "n", definition: "tác động" },
      { id: 98, term: "approach", type: "n", definition: "cách, sự tiếp cận" },
      { id: 99, term: "wisely", type: "adv", definition: "một cách khôn ngoan" },
      { id: 100, term: "sufficiently", type: "adv", definition: "đủ" }
    ],
    "The Generation Gap": [
      { id: 1, term: "generation gap", type: "n", definition: "khoảng cách thế hệ" },
      { id: 2, term: "similarity", type: "n", definition: "sự tương đồng" },
      { id: 3, term: "access", type: "n", definition: "sự tiếp cận" },
      { id: 4, term: "belief", type: "n", definition: "niềm tin" },
      { id: 5, term: "behaviour", type: "n", definition: "hành vi" },
      { id: 6, term: "nuclear family", type: "n", definition: "gia đình gồm hai thế hệ" },
      { id: 7, term: "argue", type: "v", definition: "tranh cãi" },
      { id: 8, term: "preserve", type: "v", definition: "bảo tồn" },
      { id: 9, term: "commit", type: "v", definition: "cam kết" },
      { id: 10, term: "devote", type: "v", definition: "cống hiến" },
      { id: 11, term: "extended family", type: "n", definition: "đại gia đình" },
      { id: 12, term: "conflict", type: "n", definition: "mâu thuẫn" },
      { id: 13, term: "harmony", type: "n", definition: "sự hòa hợp" },
      { id: 14, term: "duty", type: "n", definition: "trách nhiệm" },
      { id: 15, term: "dependence", type: "n", definition: "sự phụ thuộc" },
      { id: 16, term: "viewpoint", type: "n", definition: "quan điểm" },
      { id: 17, term: "potential", type: "n", definition: "tiềm năng" },
      { id: 18, term: "influence", type: "n", definition: "ảnh hưởng" },
      { id: 19, term: "respect", type: "v", definition: "tôn trọng" },
      { id: 20, term: "focus", type: "v", definition: "tập trung" },
      { id: 21, term: "homemaker", type: "n", definition: "người nội trợ" },
      { id: 22, term: "grocery", type: "n", definition: "hàng tạp hóa" },
      { id: 23, term: "chore", type: "n", definition: "việc nhà, việc vặt" },
      { id: 24, term: "breadwinner", type: "n", definition: "trụ cột gia đình" },
      { id: 25, term: "understanding", type: "n", definition: "sự thấu hiểu" },
      { id: 26, term: "characteristic", type: "n", definition: "đặc điểm" },
      { id: 27, term: "permission", type: "n", definition: "sự cho phép" },
      { id: 28, term: "experience", type: "v", definition: "trải qua" },
      { id: 29, term: "challenging", type: "adj", definition: "thách thức" },
      { id: 30, term: "curious", type: "adj", definition: "tò mò" },
      { id: 31, term: "rewarding", type: "adj", definition: "bổ ích" },
      { id: 32, term: "repetitive", type: "adj", definition: "lặp lại, nhàm chán" },
      { id: 33, term: "embrace", type: "v", definition: "đón nhận" },
      { id: 34, term: "inhabitant", type: "n", definition: "cư dân" },
      { id: 35, term: "dweller", type: "n", definition: "người cư trú" },
      { id: 36, term: "native", type: "n", definition: "người bản địa" },
      { id: 37, term: "community", type: "n", definition: "cộng đồng" },
      { id: 38, term: "enthusiastic", type: "adj", definition: "nhiệt tình" },
      { id: 39, term: "experiment", type: "v", definition: "thử nghiệm" },
      { id: 40, term: "struggle", type: "v", definition: "đấu tranh, vật lộn" },
      { id: 41, term: "expand", type: "v", definition: "mở rộng" },
      { id: 42, term: "adopt", type: "v", definition: "áp dụng" },
      { id: 43, term: "self-employed", type: "adj", definition: "tự làm chủ" },
      { id: 44, term: "hire", type: "v", definition: "thuê" },
      { id: 45, term: "bridge", type: "v", definition: "thu hẹp" },
      { id: 46, term: "adequately", type: "adv", definition: "một cách đầy đủ" },
      { id: 47, term: "strictly", type: "adv", definition: "một cách nghiêm ngặt" },
      { id: 48, term: "mutually", type: "adv", definition: "lẫn nhau" },
      { id: 49, term: "widely", type: "adv", definition: "một cách rộng rãi" },
      { id: 50, term: "progressive", type: "adj", definition: "tiến bộ" },
      { id: 51, term: "old-fashioned", type: "adj", definition: "cổ hủ, lạc hậu" },
      { id: 52, term: "easy-going", type: "adj", definition: "dễ dãi" },
      { id: 53, term: "independent", type: "adj", definition: "tự lập" },
      { id: 54, term: "controlling", type: "adj", definition: "kiểm soát" },
      { id: 55, term: "rebel", type: "v", definition: "nổi loạn" },
      { id: 56, term: "cautious", type: "adj", definition: "thận trọng" },
      { id: 57, term: "supportive", type: "adj", definition: "hỗ trợ" },
      { id: 58, term: "selfish", type: "adj", definition: "ích kỷ" },
      { id: 59, term: "attitude", type: "n", definition: "thái độ" },
      { id: 60, term: "powerless", type: "adj", definition: "bất lực" },
      { id: 61, term: "reliable", type: "adj", definition: "đáng tin cậy" },
      { id: 62, term: "relevant", type: "adj", definition: "có liên quan" },
      { id: 63, term: "puberty", type: "n", definition: "tuổi dậy thì" },
      { id: 64, term: "appealing", type: "adj", definition: "hấp dẫn" },
      { id: 65, term: "requirement", type: "n", definition: "yêu cầu" },
      { id: 66, term: "privacy", type: "n", definition: "sự riêng tư" },
      { id: 67, term: "impose", type: "v", definition: "áp đặt" },
      { id: 68, term: "model", type: "n", definition: "mô hình" },
      { id: 69, term: "curfew", type: "n", definition: "giờ giới nghiêm" },
      { id: 70, term: "adversity", type: "n", definition: "nghịch cảnh" },
      { id: 71, term: "survival", type: "n", definition: "sự sinh tồn" },
      { id: 72, term: "manner", type: "n", definition: "cách cư xử" },
      { id: 73, term: "emphasis", type: "n", definition: "sự nhấn mạnh" },
      { id: 74, term: "habit", type: "n", definition: "thói quen" },
      { id: 75, term: "afford", type: "v", definition: "đủ khả năng" },
      { id: 76, term: "renew", type: "v", definition: "gia hạn" },
      { id: 77, term: "secure", type: "v", definition: "có được" },
      { id: 78, term: "forbid", type: "v", definition: "cấm" },
      { id: 79, term: "burden", type: "n", definition: "gánh nặng" },
      { id: 80, term: "bond", type: "n", definition: "sự gắn kết" }
    ],
    "Lifelong Learning": [
      { id: 1, term: "typical", type: "adj", definition: "điển hình" },
      { id: 2, term: "distance learning", type: "n", definition: "học từ xa" },
      { id: 3, term: "achievement", type: "n", definition: "thành tựu" },
      { id: 4, term: "ambitious", type: "adj", definition: "tham vọng" },
      { id: 5, term: "pace", type: "n", definition: "tốc độ" },
      { id: 6, term: "lifelong learning", type: "n", definition: "học tập suốt đời" },
      { id: 7, term: "well-rounded", type: "adj", definition: "toàn diện" },
      { id: 8, term: "relevant", type: "adj", definition: "có liên quan, hữu ích" },
      { id: 9, term: "flexible", type: "adj", definition: "linh hoạt" },
      { id: 10, term: "boost", type: "v", definition: "tăng cường" },
      { id: 11, term: "activate", type: "v", definition: "kích hoạt" },
      { id: 12, term: "advance", type: "v", definition: "tiến bộ" },
      { id: 13, term: "analyse", type: "v", definition: "phân tích" },
      { id: 14, term: "memory", type: "n", definition: "trí nhớ" },
      { id: 15, term: "dedicate", type: "v", definition: "cống hiến" },
      { id: 16, term: "extend", type: "v", definition: "mở rộng" },
      { id: 17, term: "promote", type: "v", definition: "thúc đẩy" },
      { id: 18, term: "maintain", type: "v", definition: "duy trì" },
      { id: 19, term: "informed", type: "adj", definition: "hiểu biết, được cập nhật" },
      { id: 20, term: "passionate", type: "adj", definition: "đam mê" },
      { id: 21, term: "vulnerable", type: "adj", definition: "dễ bị tổn thương" },
      { id: 22, term: "outstanding", type: "adj", definition: "nổi bật" },
      { id: 23, term: "employ", type: "v", definition: "tuyển dụng" },
      { id: 24, term: "substitute", type: "v", definition: "thay thế" },
      { id: 25, term: "widen", type: "v", definition: "mở rộng" },
      { id: 26, term: "recruit", type: "v", definition: "chiêu mộ" },
      { id: 27, term: "motivation", type: "n", definition: "động lực" },
      { id: 28, term: "potential", type: "n", definition: "tiềm năng" },
      { id: 29, term: "influence", type: "n", definition: "ảnh hưởng" },
      { id: 30, term: "solution", type: "n", definition: "giải pháp" },
      { id: 31, term: "hardship", type: "n", definition: "khó khăn" },
      { id: 32, term: "casual", type: "adj", definition: "thông thường" },
      { id: 33, term: "cautious", type: "adj", definition: "thận trọng" },
      { id: 34, term: "strength", type: "n", definition: "sức mạnh" },
      { id: 35, term: "role", type: "n", definition: "vai trò" },
      { id: 36, term: "impact", type: "n", definition: "tác động" },
      { id: 37, term: "determination", type: "n", definition: "sự quyết tâm" },
      { id: 38, term: "obstacle", type: "n", definition: "trở ngại" },
      { id: 39, term: "qualification", type: "n", definition: "trình độ chuyên môn" },
      { id: 40, term: "shift", type: "n", definition: "ca làm việc" },
      { id: 41, term: "relationship", type: "n", definition: "mối quan hệ" },
      { id: 42, term: "stage", type: "n", definition: "giai đoạn" },
      { id: 43, term: "vacancy", type: "n", definition: "vị trí trống" },
      { id: 44, term: "distraction", type: "n", definition: "sự xao nhãng" },
      { id: 45, term: "situation", type: "n", definition: "tình huống" },
      { id: 46, term: "vocational", type: "adj", definition: "thuộc về nghề nghiệp" },
      { id: 47, term: "educational", type: "adj", definition: "thuộc về giáo dục" },
      { id: 48, term: "academic", type: "adj", definition: "học thuật" },
      { id: 49, term: "knowledge", type: "n", definition: "kiến thức" },
      { id: 50, term: "control", type: "v", definition: "kiểm soát" },
      { id: 51, term: "acquire", type: "v", definition: "đạt được" },
      { id: 52, term: "complex", type: "adj", definition: "phức tạp" },
      { id: 53, term: "aggressive", type: "adj", definition: "hung hăng" },
      { id: 54, term: "dominant", type: "adj", definition: "chiếm ưu thế" },
      { id: 55, term: "separate", type: "adj", definition: "riêng biệt" },
      { id: 56, term: "struggle", type: "v", definition: "vật lộn" },
      { id: 57, term: "liveable/livable", type: "adj", definition: "có thể sống được" },
      { id: 58, term: "active", type: "adj", definition: "năng động" },
      { id: 59, term: "personal", type: "adj", definition: "cá nhân" },
      { id: 60, term: "digital", type: "adj", definition: "kỹ thuật số" },
      { id: 61, term: "satisfying", type: "adj", definition: "thỏa mãn" },
      { id: 62, term: "enact", type: "v", definition: "ban hành" },
      { id: 63, term: "memorise", type: "v", definition: "ghi nhớ" },
      { id: 64, term: "textbook", type: "n", definition: "sách giáo khoa" },
      { id: 65, term: "reflect", type: "v", definition: "suy ngẫm" },
      { id: 66, term: "tailor", type: "v", definition: "điều chỉnh" },
      { id: 67, term: "conduct", type: "v", definition: "tiến hành" },
      { id: 68, term: "approve", type: "v", definition: "phê duyệt" },
      { id: 69, term: "support", type: "v", definition: "hỗ trợ" },
      { id: 70, term: "approach", type: "v", definition: "tiếp cận" },
      { id: 71, term: "interact", type: "v", definition: "tương tác" },
      { id: 72, term: "distribute", type: "v", definition: "phân phối" },
      { id: 73, term: "cultivate", type: "v", definition: "phát triển, nuôi dưỡng" },
      { id: 74, term: "concept", type: "n", definition: "khái niệm, ý tưởng" },
      { id: 75, term: "familiarise/familiarize", type: "v", definition: "làm quen" },
      { id: 76, term: "technological", type: "adj", definition: "thuộc công nghệ" },
      { id: 77, term: "broaden", type: "v", definition: "mở rộng" },
      { id: 78, term: "pursue", type: "v", definition: "theo đuổi" },
      { id: 79, term: "conserve", type: "v", definition: "bảo tồn" },
      { id: 80, term: "prospect", type: "n", definition: "triển vọng" },
      { id: 81, term: "valuable", type: "adj", definition: "quý giá" },
      { id: 82, term: "adaptable", type: "adj", definition: "có thể thích nghi" },
      { id: 83, term: "function", type: "n", definition: "chức năng" },
      { id: 84, term: "benefit", type: "n", definition: "lợi ích" },
      { id: 85, term: "commitment", type: "n", definition: "sự cam kết" },
      { id: 86, term: "acceptance", type: "n", definition: "sự chấp nhận" },
      { id: 87, term: "fulfilment/fulfillment", type: "n", definition: "sự thỏa mãn" },
      { id: 88, term: "refusal", type: "n", definition: "sự từ chối" },
      { id: 89, term: "costly", type: "adj", definition: "đắt đỏ" },
      { id: 90, term: "ongoing", type: "adj", definition: "đang diễn ra" },
      { id: 91, term: "familiar", type: "adj", definition: "quen thuộc" }
    ],
    "Education": [
      { id: 1, term: "utensil", type: "n", definition: "đồ dùng, dụng cụ" },
      { id: 2, term: "gadget", type: "n", definition: "dụng cụ" },
      { id: 3, term: "engine", type: "n", definition: "động cơ" },
      { id: 4, term: "tool", type: "n", definition: "công cụ" },
      { id: 5, term: "essay", type: "n", definition: "bài luận" },
      { id: 6, term: "opportunity", type: "n", definition: "cơ hội" },
      { id: 7, term: "chance", type: "n", definition: "cơ hội" },
      { id: 8, term: "advantage", type: "n", definition: "lợi thế" },
      { id: 9, term: "duty", type: "n", definition: "nghĩa vụ" },
      { id: 10, term: "target", type: "n", definition: "mục tiêu" },
      { id: 11, term: "ambition", type: "n", definition: "tham vọng" },
      { id: 12, term: "strategy", type: "n", definition: "chiến lược" },
      { id: 13, term: "attention", type: "n", definition: "sự chú ý" },
      { id: 14, term: "face-to-face", type: "adj", definition: "trực tiếp" },
      { id: 15, term: "immediate", type: "adj", definition: "ngay lập tức" },
      { id: 16, term: "imaginary", type: "adj", definition: "tưởng tượng" },
      { id: 17, term: "revise", type: "v", definition: "ôn lại, chỉnh sửa" },
      { id: 18, term: "prepare", type: "v", definition: "chuẩn bị" },
      { id: 19, term: "employ", type: "v", definition: "thuê" },
      { id: 20, term: "worthy", type: "adj", definition: "xứng đáng" },
      { id: 21, term: "available", type: "adj", definition: "có sẵn" },
      { id: 22, term: "practical", type: "adj", definition: "thực tế" },
      { id: 23, term: "reasonable", type: "adj", definition: "hợp lý" },
      { id: 24, term: "deliver", type: "v", definition: "giao" },
      { id: 25, term: "distribute", type: "v", definition: "phân phát" },
      { id: 26, term: "exchange", type: "v", definition: "trao đổi" },
      { id: 27, term: "transit", type: "v", definition: "quá cảnh" },
      { id: 28, term: "licence", type: "n", definition: "giấy phép" },
      { id: 29, term: "degree", type: "n", definition: "bằng" },
      { id: 30, term: "résumé", type: "n", definition: "lý lịch" },
      { id: 31, term: "diploma", type: "n", definition: "bằng cấp" },
      { id: 32, term: "expense", type: "n", definition: "chi phí" },
      { id: 33, term: "part-time", type: "adj/adv", definition: "bán thời gian" },
      { id: 34, term: "cover", type: "v", definition: "chi trả" },
      { id: 35, term: "assess", type: "v", definition: "đánh giá" },
      { id: 36, term: "access", type: "v", definition: "truy cập" },
      { id: 37, term: "integrate", type: "v", definition: "tích hợp" },
      { id: 38, term: "virtual reality", type: "n", definition: "thực tế ảo" },
      { id: 39, term: "stimulate", type: "v", definition: "kích thích" },
      { id: 40, term: "creativity", type: "n", definition: "sự sáng tạo" },
      { id: 41, term: "dominance", type: "n", definition: "sự thống trị" },
      { id: 42, term: "organisation", type: "n", definition: "tổ chức" },
      { id: 43, term: "responsibility", type: "n", definition: "trách nhiệm" },
      { id: 44, term: "generate", type: "v", definition: "tạo ra" },
      { id: 45, term: "gather", type: "v", definition: "tập trung, thu thập" },
      { id: 46, term: "nurture", type: "v", definition: "nuôi dưỡng" },
      { id: 47, term: "establish", type: "v", definition: "thành lập" },
      { id: 48, term: "problem-solving", type: "np", definition: "giải quyết vấn đề" },
      { id: 49, term: "expose", type: "v", definition: "tiếp xúc" },
      { id: 50, term: "complex", type: "adj", definition: "phức tạp" },
      { id: 51, term: "accessible", type: "adj", definition: "có thể truy cập" },
      { id: 52, term: "traditional", type: "adj", definition: "truyền thống" },
      { id: 53, term: "various", type: "adj", definition: "đa dạng" },
      { id: 54, term: "interactive", type: "adj", definition: "tương tác" },
      { id: 55, term: "disapprove", type: "v", definition: "không đồng tình" },
      { id: 56, term: "influence", type: "v", definition: "ảnh hưởng" },
      { id: 57, term: "depend", type: "v", definition: "phụ thuộc" },
      { id: 58, term: "consider", type: "v", definition: "xem xét, cân nhắc" },
      { id: 59, term: "attach", type: "v", definition: "đính kèm" },
      { id: 60, term: "evaluate", type: "v", definition: "đánh giá" },
      { id: 61, term: "relate", type: "v", definition: "liên quan" },
      { id: 62, term: "respond", type: "v", definition: "phản hồi" },
      { id: 63, term: "achieve", type: "v", definition: "đạt được" },
      { id: 64, term: "conduct", type: "v", definition: "tiến hành" },
      { id: 65, term: "perform", type: "v", definition: "biểu diễn" },
      { id: 66, term: "pursue", type: "v", definition: "theo đuổi" },
      { id: 67, term: "vocational", type: "adj", definition: "thuộc nghề nghiệp" },
      { id: 68, term: "stigma", type: "n", definition: "vết nhơ" },
      { id: 69, term: "consult", type: "v", definition: "hỏi ý kiến" },
      { id: 70, term: "minimal", type: "adj", definition: "tối thiểu" },
      { id: 71, term: "flexible", type: "adj", definition: "linh hoạt" },
      { id: 72, term: "respective", type: "adj", definition: "tương ứng" },
      { id: 73, term: "sensible", type: "adj", definition: "hợp lý" },
      { id: 74, term: "formal", type: "adj", definition: "chính thức" },
      { id: 75, term: "qualification", type: "n", definition: "bằng cấp" },
      { id: 76, term: "purpose", type: "n", definition: "mục đích" },
      { id: 77, term: "activity", type: "n", definition: "hoạt động" },
      { id: 78, term: "appointment", type: "n", definition: "cuộc hẹn" },
      { id: 79, term: "candidate", type: "n", definition: "ứng viên" },
      { id: 80, term: "school-leaver", type: "n", definition: "học sinh mới ra trường" },
      { id: 81, term: "appeal", type: "v", definition: "thu hút, kháng cáo, phúc khảo" },
      { id: 82, term: "control", type: "v", definition: "điều khiển" },
      { id: 83, term: "acquire", type: "v", definition: "giành được, có được" },
      { id: 84, term: "assume", type: "v", definition: "cho rằng" },
      { id: 85, term: "rapidly", type: "adv", definition: "nhanh chóng" },
      { id: 86, term: "significant", type: "adj", definition: "đáng kể" },
      { id: 87, term: "relation", type: "n", definition: "mối quan hệ" },
      { id: 88, term: "pressure", type: "n", definition: "áp lực" },
      { id: 89, term: "quality", type: "n", definition: "chất lượng" },
      { id: 90, term: "material", type: "n", definition: "chất liệu" },
      { id: 91, term: "expectation", type: "n", definition: "kỳ vọng" },
      { id: 92, term: "access", type: "n", definition: "sự truy cập" },
      { id: 93, term: "habit", type: "n", definition: "thói quen" },
      { id: 94, term: "agreement", type: "n", definition: "hiệp định" },
      { id: 95, term: "experience", type: "n", definition: "trải nghiệm" },
      { id: 96, term: "requirement", type: "n", definition: "yêu cầu" },
      { id: 97, term: "occasion", type: "n", definition: "dịp" },
      { id: 98, term: "demand", type: "n", definition: "yêu cầu" },
      { id: 99, term: "appeal", type: "n", definition: "sự hấp dẫn" },
      { id: 100, term: "licence", type: "n", definition: "giấy phép" },
      { id: 101, term: "certificate", type: "n", definition: "chứng chỉ" },
      { id: 102, term: "path", type: "n", definition: "con đường" },
      { id: 103, term: "entry", type: "n", definition: "lối vào" },
      { id: 104, term: "entrance", type: "n", definition: "đầu vào" },
      { id: 105, term: "passage", type: "n", definition: "hành lang" },
      { id: 106, term: "assessment", type: "n", definition: "đánh giá" },
      { id: 107, term: "advantage", type: "n", definition: "lợi thế" },
      { id: 108, term: "achievement", type: "n", definition: "thành tích" },
      { id: 109, term: "attainment", type: "n", definition: "sự đạt được" },
      { id: 110, term: "process", type: "v", definition: "xử lý" },
      { id: 111, term: "inform", type: "v", definition: "thông báo" },
      { id: 112, term: "satisfy", type: "v", definition: "thỏa mãn" },
      { id: 113, term: "gain", type: "v", definition: "đạt được" },
      { id: 114, term: "institution", type: "n", definition: "tổ chức, cơ sở" },
      { id: 115, term: "character", type: "n", definition: "nhân vật" },
      { id: 116, term: "journey", type: "n", definition: "hành trình" },
      { id: 117, term: "prestigious", type: "adj", definition: "danh tiếng" },
      { id: 118, term: "optional", type: "adj", definition: "không bắt buộc" },
      { id: 119, term: "complicated", type: "adj", definition: "phức tạp" },
      { id: 120, term: "serious", type: "adj", definition: "nghiêm túc" },
      { id: 121, term: "compulsory", type: "adj", definition: "bắt buộc" },
      { id: 122, term: "technique", type: "n", definition: "kỹ thuật" },
      { id: 123, term: "apprenticeship", type: "n", definition: "kỳ học việc" },
      { id: 124, term: "hands-on", type: "adj", definition: "thực tế" },
      { id: 125, term: "high-paying", type: "adj", definition: "trả lương cao" },
      { id: 126, term: "good-looking", type: "adj", definition: "ưa nhìn" },
      { id: 127, term: "well-prepared", type: "adj", definition: "được chuẩn bị kỹ" },
      { id: 128, term: "focus", type: "v", definition: "tập trung" },
      { id: 129, term: "contrast", type: "v", definition: "tương phản" },
      { id: 130, term: "distract", type: "v", definition: "làm phân tâm" },
      { id: 131, term: "enhance", type: "v", definition: "tăng cường" },
      { id: 132, term: "critical", type: "adj", definition: "có tính phản biện" },
      { id: 133, term: "informative", type: "adj", definition: "cung cấp nhiều thông tin" },
      { id: 134, term: "bachelor", type: "n", definition: "cử nhân" },
      { id: 135, term: "particular", type: "adj", definition: "cụ thể" },
      { id: 136, term: "trade", type: "n", definition: "nghề" },
      { id: 137, term: "outstanding", type: "adj", definition: "nổi bật" },
      { id: 138, term: "academic", type: "adj", definition: "thuộc học thuật" },
      { id: 139, term: "academy", type: "n", definition: "học viện" },
      { id: 140, term: "internship", type: "n", definition: "kỳ thực tập" },
      { id: 141, term: "apprentice", type: "n", definition: "người học việc" },
      { id: 142, term: "secure", type: "v", definition: "nắm chắc, có được" },
      { id: 143, term: "engaged", type: "adj", definition: "tham gia, bận rộn làm gì" },
      { id: 144, term: "informed", type: "adj", definition: "sáng suốt" },
      { id: 145, term: "appreciate", type: "v", definition: "trân trọng, coi trọng" },
      { id: 146, term: "contribute", type: "v", definition: "đóng góp" },
      { id: 147, term: "mandatory", type: "adj", definition: "có tính bắt buộc" },
      { id: 148, term: "professional", type: "adj", definition: "chuyên nghiệp" },
      { id: 149, term: "deny", type: "v", definition: "phủ nhận" },
      { id: 150, term: "approve", type: "v", definition: "chấp thuận, phê duyệt" },
      { id: 151, term: "reflect", type: "v", definition: "phản ánh" },
      { id: 152, term: "viable", type: "adj", definition: "khả thi" },
      { id: 153, term: "flexibility", type: "n", definition: "sự linh hoạt" },
      { id: 154, term: "origin", type: "n", definition: "nguồn gốc, xuất xứ" },
      { id: 155, term: "freshman", type: "n", definition: "sinh viên năm nhất" },
      { id: 156, term: "daunting", type: "adj", definition: "khó khăn" },
      { id: 157, term: "fascinating", type: "adj", definition: "lôi cuốn" },
      { id: 158, term: "budget", type: "n", definition: "ngân sách" },
      { id: 159, term: "propose", type: "v", definition: "đề xuất" },
      { id: 160, term: "eliminate", type: "v", definition: "loại bỏ" },
      { id: 161, term: "cultivate", type: "v", definition: "nuôi dưỡng, bồi đắp" },
      { id: 162, term: "passion", type: "n", definition: "niềm đam mê" },
      { id: 163, term: "concentration", type: "n", definition: "sự tập trung" },
      { id: 164, term: "trend", type: "n", definition: "xu hướng" },
      { id: 165, term: "hesitate", type: "v", definition: "chần chừ, lưỡng lự" },
      { id: 166, term: "reputation", type: "n", definition: "danh tiếng" },
      { id: 167, term: "appoint", type: "v", definition: "bổ nhiệm" },
      { id: 168, term: "enrol", type: "v", definition: "ghi danh" },
      { id: 169, term: "extracurricular", type: "adj", definition: "ngoại khóa" },
      { id: 170, term: "awareness", type: "n", definition: "sự nhận thức" },
      { id: 171, term: "demonstrate", type: "v", definition: "chứng minh" },
      { id: 172, term: "domination", type: "n", definition: "sự thống trị" },
      { id: 173, term: "commitment", type: "n", definition: "sự cam kết" },
      { id: 174, term: "distraction", type: "n", definition: "sự xao nhãng, sự phân tâm" },
      { id: 175, term: "aspect", type: "n", definition: "khía cạnh" },
      { id: 176, term: "hardship", type: "n", definition: "khó khăn" },
      { id: 177, term: "attitude", type: "n", definition: "thái độ" },
      { id: 178, term: "incident", type: "n", definition: "sự cố" },
      { id: 179, term: "value", type: "v", definition: "coi trọng, đề cao" },
      { id: 180, term: "motivation", type: "n", definition: "động lực" },
      { id: 181, term: "swiftly", type: "adv", definition: "một cách nhanh chóng" },
      { id: 182, term: "discouraged", type: "adj", definition: "nản lòng, thoái chí" },
      { id: 183, term: "reliable", type: "adj", definition: "đáng tin" },
      { id: 184, term: "virtual", type: "adj", definition: "ảo" },
      { id: 185, term: "original", type: "adj", definition: "gốc, ban đầu" },
      { id: 186, term: "emphasise", type: "v", definition: "nhấn mạnh" },
      { id: 187, term: "entirely", type: "adv", definition: "hoàn toàn" },
      { id: 188, term: "potential", type: "adj", definition: "tiềm năng" },
      { id: 189, term: "voluntary", type: "adj", definition: "có tính tự nguyện" },
      { id: 190, term: "creative", type: "adj", definition: "sáng tạo" }
    ],
    "The World of Work": [
      { id: 1, term: "stressful", type: "adj", definition: "căng thẳng" },
      { id: 2, term: "rewarding", type: "adj", definition: "đáng làm, bổ ích" },
      { id: 3, term: "shift", type: "n", definition: "ca làm việc" },
      { id: 4, term: "worsen", type: "v", definition: "trở nên xấu đi" },
      { id: 5, term: "secure", type: "v", definition: "có được, đạt được" },
      { id: 6, term: "well-paid", type: "adj", definition: "lương cao" },
      { id: 7, term: "nine-to-five", type: "phr", definition: "(công việc) giờ hành chính" },
      { id: 8, term: "career", type: "n", definition: "sự nghiệp" },
      { id: 9, term: "intern", type: "n", definition: "thực tập sinh" },
      { id: 10, term: "regulation", type: "n", definition: "quy định" },
      { id: 11, term: "maintain", type: "v", definition: "duy trì" },
      { id: 12, term: "client", type: "n", definition: "khách hàng" },
      { id: 13, term: "constantly", type: "adv", definition: "liên tục" },
      { id: 14, term: "overtime", type: "n", definition: "thêm giờ, ngoài giờ" },
      { id: 15, term: "hesitant", type: "adj", definition: "do dự, lưỡng lự" },
      { id: 16, term: "submit", type: "v", definition: "nộp" },
      { id: 17, term: "application", type: "n", definition: "đơn xin việc" },
      { id: 18, term: "hire", type: "v", definition: "thuê" },
      { id: 19, term: "challenging", type: "adj", definition: "đầy thách thức" },
      { id: 20, term: "generous", type: "adj", definition: "lớn, hậu hĩnh" },
      { id: 21, term: "bonus", type: "n", definition: "tiền thưởng" },
      { id: 22, term: "supplier", type: "n", definition: "nhà cung cấp" },
      { id: 23, term: "relevant", type: "adj", definition: "liên quan" },
      { id: 24, term: "qualification", type: "n", definition: "trình độ chuyên môn, bằng cấp" },
      { id: 25, term: "demanding", type: "adj", definition: "đòi hỏi" },
      { id: 26, term: "flexibility", type: "n", definition: "sự linh hoạt" },
      { id: 27, term: "advance", type: "v", definition: "phát triển, tiến bộ" },
      { id: 28, term: "telecommuting", type: "n", definition: "làm việc từ xa" },
      { id: 29, term: "department", type: "n", definition: "phòng ban" },
      { id: 30, term: "vacancy", type: "n", definition: "chỗ trống" },
      { id: 31, term: "candidate", type: "n", definition: "ứng viên" },
      { id: 32, term: "flexible", type: "adj", definition: "linh hoạt" },
      { id: 33, term: "communicate", type: "v", definition: "truyền đạt" },
      { id: 34, term: "hands-on", type: "adj", definition: "thực tiễn" },
      { id: 35, term: "supervise", type: "v", definition: "giám sát" },
      { id: 36, term: "casual", type: "adj", definition: "tạm thời, thời vụ" },
      { id: 37, term: "gain", type: "v", definition: "có được" },
      { id: 38, term: "practical", type: "adj", definition: "thực tiễn" },
      { id: 39, term: "organised", type: "adj", definition: "có tổ chức" },
      { id: 40, term: "attendance", type: "n", definition: "điểm danh" },
      { id: 41, term: "enthusiastic", type: "adj", definition: "nhiệt tình" },
      { id: 42, term: "reliable", type: "adj", definition: "đáng tin cậy" },
      { id: 43, term: "repetitive", type: "adj", definition: "lặp đi lặp lại, nhàm chán" },
      { id: 44, term: "interfere", type: "v", definition: "can thiệp" },
      { id: 45, term: "punctual", type: "adj", definition: "đúng giờ" },
      { id: 46, term: "endure", type: "v", definition: "chịu đựng" },
      { id: 47, term: "professional", type: "adj", definition: "chuyên nghiệp" },
      { id: 48, term: "tough", type: "adj", definition: "khó khăn" },
      { id: 49, term: "enthusiasm", type: "n", definition: "sự nhiệt tình" },
      { id: 50, term: "vocational", type: "adj", definition: "liên quan tới đào tạo nghề" },
      { id: 51, term: "specific", type: "adj", definition: "cụ thể" },
      { id: 52, term: "course", type: "n", definition: "khóa học" },
      { id: 53, term: "subject", type: "n", definition: "môn học" },
      { id: 54, term: "concept", type: "n", definition: "khái niệm, ý tưởng" },
      { id: 55, term: "trade", type: "n", definition: "nghề" },
      { id: 56, term: "abstract", type: "adj", definition: "trừu tượng" },
      { id: 57, term: "wage", type: "n", definition: "tiền công" },
      { id: 58, term: "cover", type: "v", definition: "trang trải, chi trả" },
      { id: 59, term: "generate", type: "v", definition: "tạo ra" },
      { id: 60, term: "formal", type: "adj", definition: "chính thức, chính quy" },
      { id: 61, term: "pension", type: "n", definition: "lương hưu" },
      { id: 62, term: "salary", type: "n", definition: "tiền lương" },
      { id: 63, term: "fare", type: "n", definition: "tiền vé (tàu, xe...)" },
      { id: 64, term: "fine", type: "n", definition: "tiền phạt" },
      { id: 65, term: "adequate", type: "adj", definition: "đầy đủ" },
      { id: 66, term: "clothe", type: "v", definition: "cung cấp quần áo" },
      { id: 67, term: "apprenticeship", type: "n", definition: "học việc" },
      { id: 68, term: "institution", type: "n", definition: "tổ chức" },
      { id: 69, term: "reference", type: "n", definition: "tham khảo, sự giới thiệu" },
      { id: 70, term: "ever-changing", type: "adj", definition: "thay đổi liên tục" },
      { id: 71, term: "adaptable", type: "adj", definition: "dễ thích nghi" },
      { id: 72, term: "clerk", type: "n", definition: "nhân viên (cửa hàng)" },
      { id: 73, term: "patient", type: "adj", definition: "kiên nhẫn" },
      { id: 74, term: "obey", type: "v", definition: "tuân theo" },
      { id: 75, term: "multitask", type: "v", definition: "làm nhiều việc cùng lúc" },
      { id: 76, term: "leadership", type: "n", definition: "khả năng lãnh đạo" },
      { id: 77, term: "managerial", type: "adj", definition: "liên quan tới quản lý" },
      { id: 78, term: "explanation", type: "n", definition: "giải thích" },
      { id: 79, term: "sympathetic", type: "adj", definition: "thông cảm" },
      { id: 80, term: "employ", type: "v", definition: "tuyển dụng; sử dụng" },
      { id: 81, term: "technique", type: "n", definition: "kỹ thuật" },
      { id: 82, term: "perk", type: "n", definition: "phúc lợi" },
      { id: 83, term: "prospect", type: "n", definition: "triển vọng" },
      { id: 84, term: "conflict", type: "n", definition: "xung đột" },
      { id: 85, term: "firm", type: "n", definition: "công ty" },
      { id: 86, term: "compile", type: "v", definition: "biên soạn" },
      { id: 87, term: "gather", type: "v", definition: "thu thập" },
      { id: 88, term: "immediate", type: "adj", definition: "ngay lập tức" },
      { id: 89, term: "advisable", type: "adj", definition: "nên làm" },
      { id: 90, term: "résumé", type: "n", definition: "sơ yếu lý lịch" },
      { id: 91, term: "tailor", type: "v", definition: "điều chỉnh cho phù hợp" },
      { id: 92, term: "occupation", type: "n", definition: "nghề nghiệp" },
      { id: 93, term: "criterion", type: "n", definition: "tiêu chí" },
      { id: 94, term: "representative", type: "adj/n", definition: "đại diện" },
      { id: 95, term: "complaint", type: "n", definition: "khiếu nại" },
      { id: 96, term: "allocate", type: "v", definition: "phân bổ" },
      { id: 97, term: "neglect", type: "v", definition: "bỏ bê" },
      { id: 98, term: "handle", type: "v", definition: "xử lý" },
      { id: 99, term: "run", type: "v", definition: "chạy; vận hành" },
      { id: 100, term: "financial", type: "n", definition: "tài chính" },
      { id: 101, term: "considerable", type: "adj", definition: "đáng kể" },
      { id: 102, term: "target", type: "v", definition: "nhắm đến mục tiêu nào đó" },
      { id: 103, term: "fulfilling", type: "adj", definition: "mang lại thỏa mãn" },
      { id: 104, term: "willingness", type: "n", definition: "sẵn lòng" },
      { id: 105, term: "meticulous", type: "adj", definition: "tỉ mỉ" },
      { id: 106, term: "temporary", type: "adj", definition: "tạm thời" },
      { id: 107, term: "crucial", type: "adj", definition: "quan trọng" },
      { id: 108, term: "cooperative", type: "adj", definition: "hợp tác" },
      { id: 109, term: "hostile", type: "adj", definition: "thù địch" },
      { id: 110, term: "decisive", type: "adj", definition: "quyết đoán" },
      { id: 111, term: "approachable", type: "adj", definition: "dễ gần" },
      { id: 112, term: "recruit", type: "n", definition: "lính mới, tân binh" },
      { id: 113, term: "empathetic", type: "adj", definition: "thấu cảm" },
      { id: 114, term: "productivity", type: "n", definition: "năng suất" },
      { id: 115, term: "hierarchy", type: "n", definition: "hệ thống phân cấp" },
      { id: 116, term: "rigid", type: "adj", definition: "cứng nhắc" },
      { id: 117, term: "tension", type: "n", definition: "căng thẳng" },
      { id: 118, term: "responsive", type: "adj", definition: "nhanh chóng phản ứng" },
      { id: 119, term: "enhance", type: "v", definition: "nâng cao" },
      { id: 120, term: "pursue", type: "v", definition: "theo đuổi" }
    ],
    "Social Issues": [
      { id: 1, term: "permission", type: "n", definition: "sự cho phép" },
      { id: 2, term: "contribution", type: "n", definition: "đóng góp" },
      { id: 3, term: "awareness", type: "n", definition: "nhận thức" },
      { id: 4, term: "campaign", type: "n", definition: "chiến dịch" },
      { id: 5, term: "vape", type: "v", definition: "hút thuốc lá điện tử" },
      { id: 6, term: "equal", type: "adj", definition: "bình đẳng" },
      { id: 7, term: "pressing", type: "adj", definition: "nhức nhối, cấp bách" },
      { id: 8, term: "issue", type: "n", definition: "vấn đề" },
      { id: 9, term: "street crime", type: "n", definition: "tội phạm đường phố" },
      { id: 10, term: "security", type: "n", definition: "an ninh" },
      { id: 11, term: "observation", type: "n", definition: "quan sát" },
      { id: 12, term: "measure", type: "n", definition: "biện pháp" },
      { id: 13, term: "overpopulation", type: "n", definition: "sự quá tải dân số" },
      { id: 14, term: "traffic", type: "n", definition: "giao thông" },
      { id: 15, term: "congestion", type: "n", definition: "sự tắc nghẽn" },
      { id: 16, term: "collaborate", type: "v", definition: "hợp tác" },
      { id: 17, term: "employ", type: "v", definition: "tuyển, sử dụng" },
      { id: 18, term: "assess", type: "v", definition: "đánh giá" },
      { id: 19, term: "address", type: "v", definition: "giải quyết" },
      { id: 20, term: "access", type: "v", definition: "truy cập" },
      { id: 21, term: "cyberbullying", type: "n", definition: "bắt nạt trên mạng" },
      { id: 22, term: "traffic jam", type: "n", definition: "tắc đường" },
      { id: 23, term: "peer pressure", type: "n", definition: "áp lực đồng trang lứa" },
      { id: 24, term: "fashionable", type: "adj", definition: "thời trang" },
      { id: 25, term: "challenge", type: "n", definition: "thử thách" },
      { id: 26, term: "body shaming", type: "n", definition: "miệt thị ngoại hình" },
      { id: 27, term: "devote", type: "v", definition: "cống hiến" },
      { id: 28, term: "struggle", type: "v", definition: "vật lộn" },
      { id: 29, term: "analyse", type: "v", definition: "phân tích" },
      { id: 30, term: "interact", type: "v", definition: "tương tác" },
      { id: 31, term: "midlife crisis", type: "n", definition: "khủng hoảng tuổi trung niên" },
      { id: 32, term: "severe", type: "adj", definition: "nghiêm trọng" },
      { id: 33, term: "natural disaster", type: "n", definition: "thiên tai" },
      { id: 34, term: "face", type: "v", definition: "đối mặt" },
      { id: 35, term: "hire", type: "v", definition: "thuê" },
      { id: 36, term: "bridge", type: "v", definition: "thu hẹp" },
      { id: 37, term: "mutual", type: "adj", definition: "lẫn nhau" },
      { id: 38, term: "original", type: "adj", definition: "nguyên bản" },
      { id: 39, term: "interactive", type: "adj", definition: "tương tác" },
      { id: 40, term: "violent", type: "adj", definition: "bạo lực" },
      { id: 41, term: "detain", type: "v", definition: "giam giữ" },
      { id: 42, term: "conflict", type: "n", definition: "xung đột" },
      { id: 43, term: "biodiversity", type: "n", definition: "đa dạng sinh học" },
      { id: 44, term: "poverty", type: "n", definition: "nghèo đói" },
      { id: 45, term: "gap", type: "n", definition: "khoảng cách" },
      { id: 46, term: "alcohol", type: "n", definition: "rượu" },
      { id: 47, term: "immune system", type: "n", definition: "hệ miễn dịch" },
      { id: 48, term: "hesitate", type: "v", definition: "ngần ngại" },
      { id: 49, term: "activate", type: "v", definition: "kích hoạt" },
      { id: 50, term: "dedicate", type: "v", definition: "cống hiến" },
      { id: 51, term: "depression", type: "n", definition: "bệnh trầm cảm" },
      { id: 52, term: "verbal bullying", type: "n", definition: "bắt nạt bằng lời nói" },
      { id: 53, term: "self-confidence", type: "n", definition: "sự tự tin vào bản thân" },
      { id: 54, term: "distance", type: "n", definition: "khoảng cách" },
      { id: 55, term: "promotion", type: "n", definition: "sự thăng tiến, sự quảng bá, sự xúc tiến" },
      { id: 56, term: "offensive", type: "adj", definition: "mang tính xúc phạm" },
      { id: 57, term: "alcoholic", type: "adj", definition: "có cồn" },
      { id: 58, term: "reliable", type: "adj", definition: "đáng tin cậy" },
      { id: 59, term: "lie", type: "v", definition: "nói dối" },
      { id: 60, term: "ashamed", type: "adj", definition: "xấu hổ" },
      { id: 61, term: "background", type: "n", definition: "hoàn cảnh, nền tảng" },
      { id: 62, term: "charity", type: "n", definition: "từ thiện" },
      { id: 63, term: "organisation", type: "n", definition: "tổ chức" },
      { id: 64, term: "relief", type: "n", definition: "viện trợ, cứu trợ" },
      { id: 65, term: "victim", type: "n", definition: "nạn nhân" },
      { id: 66, term: "agent", type: "n", definition: "đại lý" },
      { id: 67, term: "officer", type: "n", definition: "sĩ quan" },
      { id: 68, term: "protester", type: "n", definition: "người biểu tình" },
      { id: 69, term: "function", type: "v", definition: "hoạt động" },
      { id: 70, term: "expand", type: "v", definition: "mở rộng" },
      { id: 71, term: "upgrade", type: "v", definition: "nâng cấp" },
      { id: 72, term: "demonstrate", type: "v", definition: "biểu tình" },
      { id: 73, term: "inequality", type: "n", definition: "bất bình đẳng" },
      { id: 74, term: "offence", type: "n", definition: "tội" },
      { id: 75, term: "petition", type: "n", definition: "đơn kiến nghị" },
      { id: 76, term: "billboard", type: "n", definition: "biển quảng cáo" },
      { id: 77, term: "flash flood", type: "n", definition: "lũ quét" },
      { id: 78, term: "landslide", type: "n", definition: "sạt lở đất" },
      { id: 79, term: "widespread", type: "adj", definition: "lan rộng" },
      { id: 80, term: "famine", type: "n", definition: "nạn đói" },
      { id: 81, term: "civil war", type: "n", definition: "nội chiến" },
      { id: 82, term: "homelessness", type: "n", definition: "tình trạng vô gia cư" },
      { id: 83, term: "demolish", type: "v", definition: "phá dỡ" },
      { id: 84, term: "viral", type: "adj", definition: "nổi tiếng, lan truyền" },
      { id: 85, term: "motivate", type: "v", definition: "thúc đẩy" },
      { id: 86, term: "initiate", type: "v", definition: "khởi xướng" },
      { id: 87, term: "authority", type: "n", definition: "chính quyền" },
      { id: 88, term: "vandalism", type: "n", definition: "phá hoại" },
      { id: 89, term: "placard", type: "n", definition: "tấm biển" },
      { id: 90, term: "adjustment", type: "n", definition: "điều chỉnh" },
      { id: 91, term: "compliment", type: "n", definition: "lời khen" },
      { id: 92, term: "activist", type: "n", definition: "nhà hoạt động" },
      { id: 93, term: "climate change", type: "n", definition: "biến đổi khí hậu" },
      { id: 94, term: "fluctuation", type: "n", definition: "sự biến động" },
      { id: 95, term: "labour market", type: "n", definition: "thị trường lao động" },
      { id: 96, term: "remain", type: "v", definition: "giữ, vẫn" },
      { id: 97, term: "diversity", type: "n", definition: "sự đa dạng" },
      { id: 98, term: "unemployment", type: "n", definition: "tình trạng thất nghiệp" },
      { id: 99, term: "infrastructure", type: "n", definition: "cơ sở hạ tầng" },
      { id: 100, term: "influx", type: "n", definition: "sự đổ xô, lượng lớn gì đó" },
      { id: 101, term: "rural", type: "adj", definition: "thuộc nông thôn" },
      { id: 102, term: "migrant", type: "n", definition: "người di cư" },
      { id: 103, term: "overcrowding", type: "n", definition: "quá đông đúc" },
      { id: 104, term: "pandemic", type: "n", definition: "đại dịch" },
      { id: 105, term: "addiction", type: "n", definition: "sự nghiện" },
      { id: 106, term: "heritage", type: "n", definition: "di sản" },
      { id: 107, term: "consumption", type: "n", definition: "sự tiêu thụ" },
      { id: 108, term: "constant", type: "adj", definition: "liên tục" },
      { id: 109, term: "obesity", type: "n", definition: "béo phì" },
      { id: 110, term: "renewable", type: "adj", definition: "có thể tái tạo" },
      { id: 111, term: "invest", type: "v", definition: "đầu tư" },
      { id: 112, term: "hunger", type: "n", definition: "nạn đói" },
      { id: 113, term: "eradicate", type: "v", definition: "xóa bỏ" },
      { id: 114, term: "ghost city", type: "n", definition: "thành phố ma" },
      { id: 115, term: "overweight", type: "adj", definition: "thừa cân" },
      { id: 116, term: "overload", type: "v", definition: "làm cho quá tải" },
      { id: 117, term: "deforestation", type: "n", definition: "nạn phá rừng" },
      { id: 118, term: "sanitation", type: "n", definition: "vệ sinh" },
      { id: 119, term: "infectious", type: "adj", definition: "truyền nhiễm" },
      { id: 120, term: "outbreak", type: "n", definition: "bùng phát" },
      { id: 121, term: "urgent", type: "n", definition: "khẩn cấp" },
      { id: 122, term: "workplace", type: "n", definition: "nơi làm việc" },
      { id: 123, term: "sexism", type: "n", definition: "phân biệt giới tính" },
      { id: 124, term: "racism", type: "n", definition: "phân biệt chủng tộc" },
      { id: 125, term: "nuclear war", type: "n", definition: "chiến tranh hạt nhân" },
      { id: 126, term: "depletion", type: "n", definition: "sự suy giảm, cạn kiệt" },
      { id: 127, term: "bullying", type: "n", definition: "bắt nạt" },
      { id: 128, term: "healthcare", type: "n", definition: "chăm sóc sức khỏe" },
      { id: 129, term: "affordable", type: "adj", definition: "giá cả phải chăng" },
      { id: 130, term: "low-income", type: "adj", definition: "thu nhập thấp" },
      { id: 131, term: "individual", type: "n", definition: "cá nhân" },
      { id: 132, term: "flood-stricken", type: "adj", definition: "bị lũ lụt" },
      { id: 133, term: "fund", type: "n", definition: "quỹ" },
      { id: 134, term: "proceeds", type: "n", definition: "tiền thu được" },
      { id: 135, term: "auction", type: "n", definition: "cuộc đấu giá" },
      { id: 136, term: "playground", type: "n", definition: "sân chơi" },
      { id: 137, term: "prediction", type: "n", definition: "dự đoán" },
      { id: 138, term: "crisis", type: "n", definition: "khủng hoảng" },
      { id: 139, term: "preservative", type: "n", definition: "chất bảo quản" },
      { id: 140, term: "symptom", type: "n", definition: "triệu chứng" },
      { id: 141, term: "malnutrition", type: "n", definition: "suy dinh dưỡng" },
      { id: 142, term: "life-threatening", type: "adj", definition: "đe dọa đến tính mạng" },
      { id: 143, term: "gender discrimination", type: "n", definition: "phân biệt giới tính" },
      { id: 144, term: "shelter", type: "n", definition: "nơi trú ẩn" },
      { id: 145, term: "temporary", type: "adj", definition: "tạm thời" },
      { id: 146, term: "heatwave", type: "n", definition: "đợt nắng nóng" },
      { id: 147, term: "obese", type: "adj", definition: "béo phì" },
      { id: 148, term: "extreme", type: "adj", definition: "khắc nghiệt, cực đoan" },
      { id: 149, term: "adequate", type: "adj", definition: "đủ" },
      { id: 150, term: "slum", type: "n", definition: "khu ổ chuột" },
      { id: 151, term: "anonymous", type: "adj", definition: "ẩn danh" },
      { id: 152, term: "flood", type: "v", definition: "gây ngập lụt" },
      { id: 153, term: "yield", type: "n", definition: "năng suất, sản lượng" },
      { id: 154, term: "threat", type: "n", definition: "mối đe dọa" },
      { id: 155, term: "drought", type: "n", definition: "hạn hán" }
    ],
    "Technology": [
      { id: 1, term: "technological", type: "adj", definition: "về công nghệ" },
      { id: 2, term: "advance", type: "n", definition: "tiến bộ" },
      { id: 3, term: "express", type: "v", definition: "bày tỏ" },
      { id: 4, term: "communicate", type: "v", definition: "giao tiếp" },
      { id: 5, term: "convenient", type: "adj", definition: "thuận tiện" },
      { id: 6, term: "emotional", type: "adj", definition: "liên quan tới cảm xúc" },
      { id: 7, term: "legal", type: "adj", definition: "hợp pháp" },
      { id: 8, term: "comparative", type: "adj", definition: "so sánh, tương đối" },
      { id: 9, term: "mobile", type: "adj", definition: "di động" },
      { id: 10, term: "application", type: "n", definition: "ứng dụng" },
      { id: 11, term: "humanoid", type: "adj", definition: "hình nhân" },
      { id: 12, term: "artificial intelligence", type: "np", definition: "trí tuệ nhân tạo" },
      { id: 13, term: "invent", type: "v", definition: "phát minh" },
      { id: 14, term: "capable", type: "adj", definition: "có khả năng" },
      { id: 15, term: "portable", type: "adj", definition: "di động, dễ dàng mang theo" },
      { id: 16, term: "accessible", type: "adj", definition: "dễ tiếp cận" },
      { id: 17, term: "alternative", type: "adj", definition: "thay thế" },
      { id: 18, term: "secretly", type: "adv", definition: "bí mật" },
      { id: 19, term: "instantly", type: "adv", definition: "ngay lập tức" },
      { id: 20, term: "access", type: "n", definition: "quyền truy cập, sự tiếp cận" },
      { id: 21, term: "priority", type: "n", definition: "ưu tiên" },
      { id: 22, term: "affair", type: "n", definition: "sự kiện, vấn đề" },
      { id: 23, term: "network", type: "n", definition: "mạng lưới" },
      { id: 24, term: "luxury", type: "n", definition: "điều xa xỉ" },
      { id: 25, term: "face-to-face", type: "adj", definition: "trực tiếp" },
      { id: 26, term: "interact", type: "v", definition: "tương tác" },
      { id: 27, term: "attach", type: "v", definition: "gắn, đính kèm" },
      { id: 28, term: "display", type: "v", definition: "trưng bày" },
      { id: 29, term: "respond", type: "v", definition: "phản hồi" },
      { id: 30, term: "forward", type: "v", definition: "chuyển tiếp" },
      { id: 31, term: "high-tech", type: "adj", definition: "công nghệ cao" },
      { id: 32, term: "gadget", type: "n", definition: "công cụ, thiết bị" },
      { id: 33, term: "utensil", type: "n", definition: "dụng cụ" },
      { id: 34, term: "appliance", type: "n", definition: "thiết bị, công cụ (trong nhà)" },
      { id: 35, term: "accessory", type: "n", definition: "phụ kiện" },
      { id: 36, term: "update", type: "v", definition: "cập nhật" },
      { id: 37, term: "browse", type: "v", definition: "duyệt, lướt" },
      { id: 38, term: "upload", type: "v", definition: "đăng tải" },
      { id: 39, term: "handle", type: "v", definition: "xử lý" },
      { id: 40, term: "disease", type: "n", definition: "căn bệnh" },
      { id: 41, term: "geek", type: "n", definition: "người sành sỏi về thứ gì" },
      { id: 42, term: "extensive", type: "adj", definition: "phong phú, rộng" },
      { id: 43, term: "knowledge", type: "n", definition: "kiến thức" },
      { id: 44, term: "wearable", type: "adj", definition: "đeo được" },
      { id: 45, term: "monitor", type: "v", definition: "theo dõi" },
      { id: 46, term: "fitness", type: "n", definition: "thể chất, thể lực" },
      { id: 47, term: "grasp", type: "n", definition: "sự hiểu biết" },
      { id: 48, term: "hinder", type: "v", definition: "cản trở" },
      { id: 49, term: "adolescent", type: "n", definition: "thiếu niên" },
      { id: 50, term: "impaired", type: "adj", definition: "bị suy yếu, khuyết tật" },
      { id: 51, term: "obsessed", type: "adj", definition: "ám ảnh" },
      { id: 52, term: "distracted", type: "adj", definition: "bị phân tâm" },
      { id: 53, term: "mental health", type: "np", definition: "sức khỏe tinh thần" },
      { id: 54, term: "immense", type: "adj", definition: "to lớn" },
      { id: 55, term: "dependent", type: "adj", definition: "lệ thuộc" },
      { id: 56, term: "exhibition", type: "n", definition: "triển lãm" },
      { id: 57, term: "captivate", type: "v", definition: "thu hút" },
      { id: 58, term: "concept", type: "n", definition: "khái niệm, ý tưởng" },
      { id: 59, term: "digital", type: "adj", definition: "kỹ thuật số" },
      { id: 60, term: "automatic", type: "adj", definition: "tự động" },
      { id: 61, term: "fashionable", type: "adj", definition: "thời thượng" },
      { id: 62, term: "tutor", type: "n", definition: "gia sư" },
      { id: 63, term: "disabled", type: "adj", definition: "khuyết tật" },
      { id: 64, term: "widespread", type: "adj", definition: "rộng rãi" },
      { id: 65, term: "pop-up", type: "n", definition: "cửa sổ bật lên" },
      { id: 66, term: "kitchenware", type: "n", definition: "đồ dùng nhà bếp" },
      { id: 67, term: "malware", type: "n", definition: "phần mềm độc hại" },
      { id: 68, term: "input", type: "v", definition: "nhập" },
      { id: 69, term: "prompt", type: "n", definition: "lời gợi ý" },
      { id: 70, term: "brainchild", type: "n", definition: "sản phẩm trí tuệ" },
      { id: 71, term: "gesture", type: "n", definition: "cử chỉ" },
      { id: 72, term: "principle", type: "n", definition: "nguyên tắc" },
      { id: 73, term: "imitate", type: "v", definition: "bắt chước" },
      { id: 74, term: "behaviour", type: "n", definition: "hành vi" },
      { id: 75, term: "depth", type: "n", definition: "chiều sâu" },
      { id: 76, term: "stressful", type: "adj", definition: "căng thẳng" },
      { id: 77, term: "rewarding", type: "adj", definition: "bổ ích" },
      { id: 78, term: "dedicated", type: "adj", definition: "tận tâm" },
      { id: 79, term: "addicted", type: "adj", definition: "nghiện" },
      { id: 80, term: "sensitive", type: "adj", definition: "nhạy cảm" },
      { id: 81, term: "selfie", type: "n", definition: "ảnh tự sướng" },
      { id: 82, term: "technical", type: "adj", definition: "kỹ thuật" },
      { id: 83, term: "virtual", type: "adj", definition: "ảo" },
      { id: 84, term: "second-hand", type: "adj", definition: "đã qua sử dụng" },
      { id: 85, term: "fragile", type: "adj", definition: "mỏng manh, dễ vỡ" },
      { id: 86, term: "resilience", type: "n", definition: "sức phục hồi, sự kiên cường" },
      { id: 87, term: "criticism", type: "n", definition: "lời chỉ trích" },
      { id: 88, term: "social media", type: "np", definition: "mạng xã hội" },
      { id: 89, term: "dissatisfaction", type: "n", definition: "sự không hài lòng" },
      { id: 90, term: "recognition", type: "n", definition: "sự công nhận" },
      { id: 91, term: "consciousness", type: "n", definition: "ý thức" },
      { id: 92, term: "familiarity", type: "n", definition: "sự quen thuộc" },
      { id: 93, term: "body image", type: "np", definition: "hình ảnh cơ thể" },
      { id: 94, term: "conflict", type: "n", definition: "xung đột" },
      { id: 95, term: "utilise", type: "v", definition: "sử dụng" },
      { id: 96, term: "specialised", type: "adj", definition: "chuyên biệt, chuyên môn" },
      { id: 97, term: "convert", type: "v", definition: "chuyển đổi" },
      { id: 98, term: "register", type: "v", definition: "đăng ký" },
      { id: 99, term: "format", type: "n", definition: "định dạng" },
      { id: 100, term: "navigate", type: "v", definition: "điều hướng" },
      { id: 101, term: "interfere", type: "v", definition: "can thiệp" },
      { id: 102, term: "replace", type: "v", definition: "thay thế" },
      { id: 103, term: "self-driving", type: "adj", definition: "không người lái" },
      { id: 104, term: "disability", type: "n", definition: "khuyết tật" },
      { id: 105, term: "benefit", type: "v", definition: "có lợi cho" },
      { id: 106, term: "obsolete", type: "adj", definition: "lỗi thời" },
      { id: 107, term: "search engine", type: "n", definition: "công cụ tìm kiếm" },
      { id: 108, term: "shape", type: "v", definition: "định hình" },
      { id: 109, term: "deliver", type: "v", definition: "thực hiện, cung cấp" },
      { id: 110, term: "platform", type: "n", definition: "nền tảng" },
      { id: 111, term: "laborious", type: "adj", definition: "tốn sức, vất vả" },
      { id: 112, term: "biassed", type: "adj", definition: "thiên vị" },
      { id: 113, term: "coverage", type: "n", definition: "sự đưa tin" },
      { id: 114, term: "visual trickery", type: "n", definition: "lừa dối thị giác" },
      { id: 115, term: "cost-effective", type: "adj", definition: "tiết kiệm chi phí" },
      { id: 116, term: "hoax", type: "n", definition: "trò lừa đảo" },
      { id: 117, term: "antisocial", type: "adj", definition: "chống đối xã hội" },
      { id: 118, term: "suspicious", type: "adj", definition: "đáng nghi" },
      { id: 119, term: "devise", type: "v", definition: "sáng chế, phát minh ra" },
      { id: 120, term: "scam", type: "n", definition: "lừa đảo" },
      { id: 121, term: "combat", type: "v", definition: "chống lại" },
      { id: 122, term: "billboard", type: "n", definition: "bảng quảng cáo" },
      { id: 123, term: "noticeable", type: "adj", definition: "đáng chú ý" },
      { id: 124, term: "loudspeaker", type: "n", definition: "loa phóng thanh" },
      { id: 125, term: "alert", type: "v", definition: "cảnh báo" },
      { id: 126, term: "fake news", type: "n", definition: "tin giả" },
      { id: 127, term: "cautious", type: "adj", definition: "cẩn trọng" },
      { id: 128, term: "promote", type: "v", definition: "xúc tiến, quảng bá" },
      { id: 129, term: "reliable", type: "adj", definition: "đáng tin cậy" },
      { id: 130, term: "minutes", type: "n", definition: "biên bản cuộc họp" },
      { id: 131, term: "accurate", type: "adj", definition: "chính xác" },
      { id: 132, term: "credible", type: "adj", definition: "có thể tin được" },
      { id: 133, term: "immediate", type: "adj", definition: "ngay lập tức" },
      { id: 134, term: "feedback", type: "n", definition: "đánh giá, phản hồi" },
      { id: 135, term: "privacy", type: "n", definition: "sự riêng tư" },
      { id: 136, term: "forum", type: "n", definition: "diễn đàn" },
      { id: 137, term: "outdated", type: "adj", definition: "lỗi thời" },
      { id: 138, term: "anonymous", type: "adj", definition: "ẩn danh" },
      { id: 139, term: "trustworthy", type: "adj", definition: "đáng tin cậy" },
      { id: 140, term: "exaggerate", type: "v", definition: "phóng đại" }
    ],
    "Urbanisation": [
      { id: 1, term: "dweller", type: "n", definition: "người cư ngụ, cư dân" },
      { id: 2, term: "routine", type: "n", definition: "thói quen, quy trình" },
      { id: 3, term: "habitat", type: "n", definition: "môi trường sống" },
      { id: 4, term: "custom", type: "n", definition: "tập quán, phong tục" },
      { id: 5, term: "economic", type: "adj", definition: "thuộc kinh tế" },
      { id: 6, term: "prosperity", type: "n", definition: "sự thịnh vượng, phồn thịnh" },
      { id: 7, term: "development", type: "n", definition: "sự phát triển" },
      { id: 8, term: "congest", type: "v", definition: "làm tắc nghẽn" },
      { id: 9, term: "interactive", type: "adj", definition: "mang tính tương tác" },
      { id: 10, term: "hands-on", type: "adj", definition: "thực tiễn, thực hành" },
      { id: 11, term: "sustainable", type: "adj", definition: "bền vững" },
      { id: 12, term: "congestion", type: "n", definition: "sự tắc nghẽn, ùn tắc" },
      { id: 13, term: "secure", type: "adj", definition: "an toàn" },
      { id: 14, term: "private", type: "adj", definition: "riêng tư" },
      { id: 15, term: "communal", type: "adj", definition: "chung, tập thể" },
      { id: 16, term: "negative", type: "adj", definition: "tiêu cực" },
      { id: 17, term: "installation", type: "n", definition: "sự lắp đặt" },
      { id: 18, term: "sensor", type: "n", definition: "cảm biến" },
      { id: 19, term: "efficient", type: "adj", definition: "hiệu quả" },
      { id: 20, term: "operate", type: "v", definition: "vận hành, điều hành" },
      { id: 21, term: "adjust", type: "v", definition: "điều chỉnh" },
      { id: 22, term: "launch", type: "v", definition: "phát động, ra mắt" },
      { id: 23, term: "typhoon", type: "n", definition: "bão" },
      { id: 24, term: "infrastructure", type: "n", definition: "cơ sở hạ tầng" },
      { id: 25, term: "communication", type: "n", definition: "giao tiếp, truyền thông" },
      { id: 26, term: "unusual", type: "adj", definition: "bất thường" },
      { id: 27, term: "architecture", type: "n", definition: "kiến trúc" },
      { id: 28, term: "skyscraper", type: "n", definition: "tòa nhà chọc trời" },
      { id: 29, term: "suburb", type: "n", definition: "ngoại ô" },
      { id: 30, term: "harmony", type: "n", definition: "sự hài hòa, hòa hợp" },
      { id: 31, term: "crime", type: "n", definition: "tội phạm" },
      { id: 32, term: "liveable/livable", type: "adj", definition: "có thể sống được, đáng sống" },
      { id: 33, term: "lifelike", type: "adj", definition: "giống thật, sống động" },
      { id: 34, term: "long-lasting", type: "adj", definition: "lâu dài, bền vững" },
      { id: 35, term: "urgent", type: "adj", definition: "khẩn cấp, cấp bách" },
      { id: 36, term: "resident", type: "n", definition: "cư dân" },
      { id: 37, term: "pedestrian", type: "n", definition: "người đi bộ" },
      { id: 38, term: "high-rise", type: "adj", definition: "cao tầng" },
      { id: 39, term: "gain", type: "v", definition: "đạt được, có được" },
      { id: 40, term: "rooftop", type: "n", definition: "mái nhà" },
      { id: 41, term: "preservation", type: "n", definition: "sự bảo tồn" },
      { id: 42, term: "invasion", type: "n", definition: "sự xâm lược" },
      { id: 43, term: "council", type: "n", definition: "hội đồng" },
      { id: 44, term: "allocate", type: "v", definition: "phân bổ, chỉ định" },
      { id: 45, term: "neighbourhood", type: "n", definition: "khu phố, khu vực xung quanh" },
      { id: 46, term: "shift", type: "n", definition: "sự thay đổi" },
      { id: 47, term: "root", type: "n", definition: "gốc, nguồn gốc" },
      { id: 48, term: "amenity", type: "n", definition: "tiện nghi, tiện ích" },
      { id: 49, term: "professional", type: "adj, n", definition: "chuyên nghiệp" },
      { id: 50, term: "residential", type: "adj", definition: "thuộc về cư dân" },
      { id: 51, term: "equal", type: "adj", definition: "bình đẳng" },
      { id: 52, term: "megacity", type: "n", definition: "siêu đô thị" },
      { id: 53, term: "overcrowded", type: "adj", definition: "quá đông đúc" },
      { id: 54, term: "migrate", type: "v", definition: "di cư, di chuyển" },
      { id: 55, term: "seek", type: "v", definition: "tìm kiếm" },
      { id: 56, term: "rural", type: "adj", definition: "thuộc nông thôn" },
      { id: 57, term: "original", type: "adj", definition: "nguyên bản, gốc" },
      { id: 58, term: "struggle", type: "v", definition: "đấu tranh, vật lộn" },
      { id: 59, term: "low-income", type: "adj", definition: "thu nhập thấp" },
      { id: 60, term: "affordable", type: "adj", definition: "phải chăng, hợp túi tiền" },
      { id: 61, term: "commute", type: "v, n", definition: "đi làm hàng ngày; việc đi làm hàng ngày" },
      { id: 62, term: "downtown", type: "n, adj", definition: "trung tâm thành phố; thuộc về trung tâm thành phố" },
      { id: 63, term: "nightmare", type: "n", definition: "cơn ác mộng, nỗi kinh hoàng" },
      { id: 64, term: "rush hour", type: "n", definition: "giờ cao điểm" },
      { id: 65, term: "convenient", type: "adj", definition: "thuận tiện" },
      { id: 66, term: "fluctuating", type: "adj", definition: "dao động, thay đổi liên tục" },
      { id: 67, term: "facility", type: "n", definition: "cơ sở vật chất" },
      { id: 68, term: "density", type: "n", definition: "mật độ" },
      { id: 69, term: "grid", type: "n", definition: "lưới điện" },
      { id: 70, term: "slum", type: "n", definition: "khu ổ chuột" },
      { id: 71, term: "facilitate", type: "v", definition: "tạo điều kiện, thuận tiện cho" },
      { id: 72, term: "spread", type: "n", definition: "sự lan truyền" },
      { id: 73, term: "wage", type: "n", definition: "tiền công" },
      { id: 74, term: "sanitation", type: "n", definition: "hệ thống vệ sinh" },
      { id: 75, term: "inequality", type: "n", definition: "sự bất bình đẳng" },
      { id: 76, term: "overpopulation", type: "n", definition: "quá đông dân" },
      { id: 77, term: "essentials", type: "n", definition: "đồ thiết yếu" },
      { id: 78, term: "overloaded", type: "adj", definition: "quá tải" },
      { id: 79, term: "expand", type: "v", definition: "mở rộng" },
      { id: 80, term: "influx", type: "n", definition: "sự đổ xô" },
      { id: 81, term: "migrant", type: "n", definition: "người di cư" },
      { id: 82, term: "considerable", type: "adj", definition: "đáng kể, khá lớn" },
      { id: 83, term: "strain", type: "n", definition: "áp lực, căng thẳng" }
    ],
};